db.url: jdbc:mysql://cafeshop.c9ieusgg00xd.us-east-1.rds.amazonaws.com:3306/cafeShopDB
db.username: cafeShop
db.password: Etp12345
db.driver: com.mysql.cj.jdbc.Driver
db.dialect: org.hibernate.dialect.MySQL8Dialect
db.hbm2ddl: update
db.show_sql: true
db.hibernate.current_session_context_class: org.hibernate.context.internal.ThreadLocalSessionContext
