eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7591/eureka


db:
  url: jdbc:mysql://cafeshop.c9ieusgg00xd.us-east-1.rds.amazonaws.com:3306/cafeShopDB
  username: cafeShop
  password: Etp12345
  driver: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL8Dialect
  hbm2ddl: update
  show_sql: true

