spring:
  application:
    name: application
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gauravgorde/config-server.git
          skipSslValidation: true
          clone-on-start: true
        
          # username: ${git_username}
          # password: ${git_password}

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7591/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
 
